# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-05 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import status.models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190805_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=status.models.upload_update_image),
        ),
    ]
